### ISSUE TITLE
How to earlystart steam minimized

### ISSUE THREAD

**Issue by FranzMaurerr** [sylveon/EarlyStart#7]
Hello, what should I add at the end of the line to make Steam open silently? not showing the window on the desktop.

**Comment by sylveon** [comment]
Why not just use steam's normal automatic startup?

**Comment by FranzMaurerr** [comment]
because using earlystart, steam starts much faster. For the SignalRGB program, I added --silent and the program runs in the tray without a window appearing on the desktop, but it doesn't work on steam

i use google translator, sorry for mistakes.

**Comment by sylveon** [comment]
Use -silent (one dash only)

**Comment by FranzMaurerr** [comment]
Thank you very much! everything works as it should! :)
